# Change these first
owner: watain666 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Always Indigo
    url: https://tiaui.co
  - name: One Drive
    url: https://d.tiaui.co/
  - name: FETN
    url: https://fetnto.blogspot.com/
    interval: 300000  # 5-minute interval instead of default 30 seconds
  - name: O͘màmà
    url: https://omama.to/
  - name: Tâijī chhân
    url: https://ji.taioan.org/
  - name: Ginger's portfolio 
    url: https://bginger.art/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.tiaui.co
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
